from sqlalchemy.orm import DeclarativeBase
from sqlalchemy import Column, String, Integer, Boolean, DateTime


# DBModelBase is imported by database.py to call create_all()
class DBModelBase(DeclarativeBase):
    pass


class CallRecord(DBModelBase):
    """
    Represents a single customer support call record for TechFlow Solutions.
    Each row captures who called, when they called, how long they waited,
    what the issue was, and whether it was resolved.
    """
    __tablename__ = "call_records"

    # Unique identifier for each call — generated by Faker's uuid4
    call_id = Column(String, primary_key=True)

    # Customer's full name — generated by Faker's name()
    customer_name = Column(String, nullable=False)

    # Full datetime of when the call came in — generated by Faker's date_time_this_year()
    call_timestamp = Column(DateTime, nullable=False)

    # Name of the day (e.g. "Monday") — derived from call_timestamp
    day_of_week = Column(String, nullable=False)

    # Hour of the day (0–23) — derived from call_timestamp
    hour_of_day = Column(Integer, nullable=False)

    # How many minutes the customer waited — generated by random, adjusted by time/day rules
    wait_time_minutes = Column(Integer, nullable=False)

    # One of: Billing, Technical, Service, Account — chosen by random array index
    issue_category = Column(String, nullable=False)

    # Whether the issue was resolved — generated by random boolean
    resolution_status = Column(Boolean, nullable=False)